[package]
name = "verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
once_cell = "1.17.1"
quit = "2.0.0"
signal-hook = "0.3.15"
nix = "0.26.2"
num_enum = "0.6.1"